<a href="https://colab.research.google.com/github/Muhammad-Faiz-Firmansyah/2026_KECERDASAAN_BUATAN/blob/main/jobsheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 2 - OPERASI MATEMATIKA, VEKTOR, DAN MATRIKS

### 1.	Tipe Data Python

a. Cek Tipe Data

In [ ]:
var = 123
print(type(var))

<class 'int'>


b. Tipe Data Python

In [ ]:
a = '123'
b = '3.4'
c = "Data String"

print(type(c))

<class 'str'>


c. Tipe data numerik

In [ ]:
var1 = 345
var2 = 34.5
f1   = float(var1)

print(type(f1))
print(f1)

sum = var1 + var2
print(sum)

var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)

<class 'float'>
345.0
379.5
34
12


d. Tipe Data boolean

In [ ]:
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

False
False
True
True


e. Tipe Data List

In [ ]:
list = ["belajar dasar python", 2023, 3.8, True]
print(list)
print(list[3])
print(list[1:3])
print(len(list))

['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


### 2. Operasi matematika menggunakan pythom

a. Mendapatkan nilai minimum dan maksimum

In [ ]:
x = min(5, 10, 25)
y = max(6, 12, 18)

print(x)
print(y)

5
18


b. mendapatkan nilai absolut

In [ ]:
x = abs(-7.25)

print(x)

7.25


c. Mendapatkan nilai pangkat

In [ ]:
import math
x = math.pow(4, 3)

print(x)

64.0


d. Mendapatkan nilai akar

In [ ]:
import math
x = math.sqrt(64)

print(x)

8.0


e. Mendapatkan nilai akar

In [ ]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)

print(x)
print(y)

2
1


f. Mendapatkan nilai konstanta (PI)

In [ ]:
import math
x = math.pi

print(x)

3.141592653589793


### 4. Operasi matriks dan vektor dengan python

a. Membuat matriks di python

In [ ]:
import numpy as np
A = np.array([[80, 30, 25], [50, 20, 10]])
B = np.array([[30, 60, 15], [10, 30, 30]])

C = A + B

print(C)

[[110  90  40]
 [ 60  50  40]]


b. Melakukan operasi dot product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

C = np.dot(A, B)

print(C)

2025


c. Melakukan operasi cross product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

C = np.cross(A, B)

print(C)

[-305 -110  350]


### PENUGASAN

PENUGASAN KE 1

In [ ]:
import numpy as np
A = np.array([[3, 1],
              [2, 0]])

B = np.array([[2, 1],
              [1, -1]])

C = np.array([[-1, 1, 2],
              [2, 0, -1]])

AB = np.dot(A,B)
BC = np.dot(B,C)

print("Hasil dari A x B adalah = \n", (AB))
print("\n")
print("Hasil dari B . C adalah = \n", (BC))

Hasil dari A x B adalah = 
 [[7 2]
 [4 2]]


Hasil dari B . C adalah = 
 [[ 0  2  3]
 [-3  1  3]]


PENUGASAN KE 2

In [ ]:
import math
A = 6
B = 8
C = 5

hasilA = math.factorial(A)
hasilB = math.factorial(B)
hasilC = math.factorial(C)

hasilBC = (hasilB // hasilC)

print(hasilA)
print(hasilBC)

720
336


PENUGASAN KE 3

In [ ]:
import numpy as np
A = [5,3,7]
B = [12,-3,1]

hasilA = np.dot(A,B)
hasilB = np.cross(A,B)

print("Hasil dari A . B adalah = \n", (hasilA))
print("\n")
print("Hasil dari A x B adalah = \n", (hasilB))

Hasil dari A . B adalah = 
 58


Hasil dari A x B adalah = 
 [ 24  79 -51]
