<a href="https://colab.research.google.com/github/Muhammad-Faiz-Firmansyah/2026_KECERDASAAN_BUATAN/blob/main/jobsheet_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#JOBSHEET 2 - OPERASI MATEMATIKA, VEKTOR, DAN MATRIKS

## 1.	Tipe Data Python

###a.	Cek Tipe Data

In [1]:
var = 123
print(type(var))

<class 'int'>


### b.	Tipe data String

In [2]:
a = '123'
b = '3.4'
c = "Data String"

print(type(c))

<class 'str'>


### c.	Tipe data numerik

In [3]:
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))

print(f1)

sum = var1 + var2
print(sum)

var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)

print(i2)


<class 'float'>
345.0
379.5
34
12


### d.	Tipe Data Boolean

In [5]:
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

False
False
True
True


###e.	Tipe Data List

In [7]:
list = ["belajar dasar python", 2023, 3.8, True]
print(list)

print(list[3])

print(list[1:3])

print(len(list))

['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


##2.	Operasi matematika menggunakan python

### a.	Mendapatkan nilai minimum dan maksimum

In [10]:
x = min(5,10,25)
y = max(6,12,18)

print(x)
print(y)

5
18


### b.	Mendapatkan nilai absolut

In [11]:
x = abs(-7.25)
print(x)

7.25


###c.	Mendapatkan nilai pangkat

In [13]:
import math
x = math.pow(4, 3)

print(x)

64.0


###d.	Mendapatkan nilai akar

In [14]:
import math
x = math.sqrt(64)

print(x)

8.0


###e.	Mendapatkan nilai pembulatan

In [15]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)

print(x)
print(y)

2
1


### f.	Mendapatkan nilai konstanta (PI)

In [17]:
import math
x = math.pi

print(x)

3.141592653589793


##4.	Operasi matriks dan vektor dengan python

###a.	Membuat matriks di pyhon

In [18]:
import numpy as np

A = np.array([
    [80,30,25],
    [50,20,10]
])

B = np.array([
    [30,60,15],
    [10,30,30]
])

hasil = A + B

print(hasil)

[[110  90  40]
 [ 60  50  40]]


### b.	Melakukan operasi dot product

In [19]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)

print(hasil)

2025


### c.	Melakukan operasi cross product

In [20]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)

print(hasil)

2025


## E.	TUGAS PRAKTIKUM

In [23]:
import numpy as np

A = np.array([
    [3, 1],
    [2, 0]
])

B = np.array([
    [2, 1],
    [1, -1]
])

C = np.array([
    [-1, 1, 2],
    [2, 0, -1]
])

hasil_AB = np.matmul(A, B)

print("A =")
print(A)

print("\nB =")
print(B)

print("\nA x B =")
print(hasil_AB)

A =
[[3 1]
 [2 0]]

B =
[[ 2  1]
 [ 1 -1]]

A x B =
[[7 2]
 [4 2]]


In [24]:
hasil_BC = np.matmul(B, C)

print("B . C =")
print(hasil_BC)

B . C =
[[ 0  2  3]
 [-3  1  3]]


In [25]:
import math

print("6! =", math.factorial(6))

6! = 720


In [26]:
hasil = math.factorial(8) // math.factorial(5)

print("8! / 5! =", hasil)

8! / 5! = 336


In [27]:
 import numpy as np

A = np.array([5,3,7])
B = np.array([12,-3,1])

panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

dot = np.dot(A,B)

cross = np.cross(A,B)

print("Panjang Vektor A =", panjang_A)
print("Panjang Vektor B =", panjang_B)

print("\nA . B =", dot)

print("\nA x B =")
print(cross)

Panjang Vektor A = 9.1104335791443
Panjang Vektor B = 12.409673645990857

A . B = 58

A x B =
[ 24  79 -51]
